from fastapi import APIRouter, Depends, status
from langchain_core.messages import HumanMessage
from app.api.v1.auth import get_current_user
from app.models.base import UserModel
from app.schemas.chat import ChatPromptRequest
from app.agents.workflow import compiled_healthcare_graph

router = APIRouter()

@router.post("/agentic-execute", status_code=status.HTTP_200_OK)
async def execute_agentic_orchestration_loop(
    payload: ChatPromptRequest,
    current_user: UserModel = Depends(get_current_user)
):
    """
    Unified execution endpoint that passes user queries to LangGraph for smart routing.
    """
    # Build initial state payload
    initial_graph_state = {
        "messages": [HumanMessage(content=payload.message)],
        "user_id": current_user.id,
        "session_id": payload.session_id,
        "next_action": "",
        "triage_evaluation": {}
    }
    
    # Run graph execution asynchronously
    final_output_state = await compiled_healthcare_graph.ainvoke(initial_graph_state)
    
    # Extract the final message generated by the selected agent node
    final_agent_message = final_output_state["messages"][-1].content
    
    return {
        "session_id": payload.session_id,
        "response": final_agent_message,
        "dispatched_path": final_output_state["next_action"]
    }